---
- name: Add Ondřej Surý PHP PPA GPG key
  apt_key:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xB8DC7E53946656EFBCE4C1DD71DAEAAB4AD4CAB6"
    keyring: /usr/share/keyrings/ondrej-php.gpg
    state: present

- name: Add ondrej/php PPA repository securely
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/ondrej-php.gpg] http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main"
    filename: ondrej-php
    state: present
    update_cache: yes

- name: Ensure PHP default packages are installed
  ansible.builtin.apt:
    name: "{{ php_default_packages }}"
    state: present

- name: Ensure PHP extra packages are installed
  ansible.builtin.apt:
    name: "{{ php_extra_packages }}"
    state: present
  