---
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Ensure PHP default packages are installed
  ansible.builtin.apt:
    name: "{{ php_default_packages }}"
    state: present

- name: Ensure PHP extra packages are installed
  ansible.builtin.apt:
    name: "{{ php_extra_packages }}"
    state: present
  