---
- name: Gather OS Specific Variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "../vars/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "../vars/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
        - "../vars/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_release'] }}.yml"
        - "../vars/{{ ansible_facts['distribution'] }}.yml"
        - "../vars/{{ ansible_facts['os_family'] }}.yml"
      skip: yes

- name: Include OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Apply default PHP settings
  community.general.ini_file:
    dest: "{{ php_ini_path }}"
    option: "{{ item.option }}"
    value: "{{ item.value|default(omit) }}"
    section: "{{ item.section }}"
  with_items: "{{ php_default_settings }}"

- name: Apply specific PHP settings
  community.general.ini_file:
    dest: "{{ php_ini_path }}"
    option: "{{ item.option }}"
    value: "{{ item.value|default(omit) }}"
    section: "{{ item.section }}"
  with_items: "{{ php_custom_settings }}"
  when: (php_custom_settings is defined) and (php_custom_settings|length > 0)

- name: Apply PHP-FPM pool settings
  ansible.builtin.template:
    src: pool.conf-{{ ansible_os_family }}.j2
    dest: "{{ php_pool_path + item.name + '.conf' }}"
    mode: 0644
  with_items: "{{ php_fpm_pools }}"
  when: php_fpm_enable|bool

- name: Apply php-fpm.conf settings
  community.general.ini_file:
    dest: "{{ php_fpm_default_conf_path }}"
    option: "{{ item.option }}"
    value: "{{ item.value|default(omit) }}"
    section: "{{ item.section }}"
  with_items: "{{ php_fpm_settings }}"
  when: php_fpm_enable|bool

- name: Start and enable PHP-FPM daemon
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: started
    enabled: yes
  when: php_fpm_enable|bool
