---
- name: Import EPEL GPG Key
  ansible.builtin.rpm_key:
    key: "{{ epel['gpg_key_url'] }}"
    state: present

- name: Install EPEL Repository
  ansible.builtin.yum:
    name: "{{ epel['repository_url'] }}"
    state: latest

- name: Import REMI GPG Key
  ansible.builtin.rpm_key:
    key: "{{ remi['gpg_key_url'] }}"
    fingerprint: "{{ remi['gpg_key_fingerprint'] }}"
    validate_certs: no
    state: present

- name: Install REMI Repository
  ansible.builtin.yum:
    name: "{{ remi['repository_url'] }}"
    state: latest

- name: Ensure PHP default packages are installed
  ansible.builtin.yum:
    name: "{{ php_default_packages }}"
    state: present

- name: Ensure PHP extra packages are installed
  ansible.builtin.yum:
    name: "{{ php_extra_packages }}"
    state: present
