---
- name: Import EPEL GPG Key
  ansible.builtin.rpm_key:
    key: "{{ epel['gpg_key_url'] }}"
    state: present

- name: Install EPEL Repository
  ansible.builtin.yum:
    name: "{{ epel['repository_url'] }}"
    state: latest

- name: Import REMI GPG Key
  ansible.builtin.rpm_key:
    key: "{{ remi['gpg_key_url'] }}"
    fingerprint: "{{ remi['gpg_key_fingerprint'] }}"
    validate_certs: no
    state: present

- name: Install REMI Repository
  ansible.builtin.yum:
    name: "{{ remi['repository_url'] }}"
    state: latest

- name: Ensure PHP default packages are installed
  ansible.builtin.yum:
    name: "{{ php_default_packages }}"
    state: present

- name: Ensure PHP extra packages are installed
  ansible.builtin.yum:
    name: "{{ php_extra_packages }}"
    state: present

- name: Configure PHP INI settings
  ansible.builtin.template:
    src: php.ini.j2
    dest: "{{ php_ini_path }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ php_ini_settings }}"

- name: Apply PHP-FPM pool settings
  ansible.builtin.template:
    src: pool.conf.j2
    dest: "{{ '/etc/opt/remi/php' + php_version|replace('.', '') + '/php-fpm.d/' + item.name + '.conf' }}"
    mode: 0644
  with_items: "{{ php_fpm_pools }}"
  when: php_fpm_enable|bool

- name: Start and enable PHP-FPM daemon
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: started
    enabled: yes
  when: php_fpm_enable|bool
