---
- name: Import EPEL GPG Key
  ansible.builtin.rpm_key:
    key: "{{ epel['gpg_key_url'] }}"
    state: present

- name: Install EPEL Repository
  ansible.builtin.yum:
    name: "{{ epel['repository_url'] }}"
    state: latest

- name: Import REMI GPG Key
  ansible.builtin.rpm_key:
    key: "{{ remi['gpg_key_url'] }}"
    fingerprint: "{{ remi['gpg_key_fingerprint'] }}"
    validate_certs: no
    state: present

- name: Install REMI Repository
  ansible.builtin.yum:
    name: "{{ remi['repository_url'] }}"
    state: latest

- name: Ensure PHP default packages are installed
  ansible.builtin.yum:
    name: "{{ php_default_packages }}"
    state: present

- name: Ensure PHP extra packages are installed
  ansible.builtin.yum:
    name: "{{ php_extra_packages }}"
    state: present

- name: Apply default PHP settings (php.ini)
  ansible.builtin.lineinfile:
    path: "{{ php_ini_path }}" 
    regexp: "{{ item.regexp }}"  
    line: "{{ item.line }}"  
    state: "{{ item.state | default('present') }}" 
  with_items: "{{ php_default_settings }}"
  when: apply_php_default_settings|bool

- name: Apply custom PHP settings
  ansible.builtin.lineinfile:
    path: "{{ php_ini_path }}" 
    regexp: "{{ item.regexp }}"  
    line: "{{ item.line }}"  
    state: "{{ item.state | default('present') }}" 
  with_items: "{{ php_extra_settings }}"

- name: Apply PHP default pool settings
  ansible.builtin.lineinfile:
    path: "{{ php_pool_path }}" 
    regexp: "{{ item.regexp }}"  
    line: "{{ item.line }}"  
    state: "{{ item.state | default('present') }}" 
  with_items: "{{ php_default_pool }}"
  when: (apply_php_default_pool|bool) and (php_fpm_enable|bool)

- name: Apply custom PHP default pool settings
  ansible.builtin.lineinfile:
    path: "{{ php_pool_path }}" 
    regexp: "{{ item.regexp }}"  
    line: "{{ item.line }}"  
    state: "{{ item.state | default('present') }}" 
  with_items: "{{ php_pool }}"
  when: php_fpm_enable|bool

- name: Start and enable PHP-FPM daemon
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: started
    enabled: yes
  when: php_fpm_enable|bool
