---
- name: php-fpm-start
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: started

- name: php-fpm-restart
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: restarted

- name: php-fpm-stop
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: stopped
